# Wk 1 Introduction to Remote Sensing

## Summary

As a relative newbie to Remote Sensing there was so much new information this week that it's very difficult to choose even a few things to talk about without writing an whole essay. Therefore I have decided that the best way to summarise this would be through a mind map.



## Application

For a specific topic from this week identify two readings and summarise them and then provide a comparison of the two. Raise any questions related to the topic.

??Look at how bands differ between sensor (Landsat and Sentinel) and also how different bands can be combined for different purposes??

### Reading 1

Talk about key findings from this reading

### Reading 2

Then talk about key findings from this reading

### Comparison

Provide a comparison between the two readings, but ensure that individual thought is included. So do I agree with what is discussed, could further clarification or research benefit the article.

## Reflection

Discuss how the skills, tools, etc. could be put into practice and how this could or could not be useful in future.
